version: '3'
services:
  dev:
    image: node:12
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    env_file: ../.env
    working_dir: /app
    command: yarn dev 

    # ports:
    #   - 1234:1234
    #   - 1235:1235

volumes:
  nodemodules:
    external: true
