{
 "title": "Bee Network  ETF Balance Watch",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "3BBULL",
    "query": "select currworth from worth where symbol='3BBULL'"
   },
   {
    "name": "3BBEAR",
    "query": "select currworth from worth where symbol='3BBEAR'"
   }
  ]
 },
 "panels": [
  {
   "title": "牛熊差额",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsum(bear)  -sum(bull) \n \nfrom assets  \n"
    }
   ]
  },
  {
   "title": "地址资产数量",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsum(bull) as bulls,\nsum(bear) as bears,\nsum(usdt) as usdts \nfrom assets  \n"
    }
   ]
  },
  {
   "title": "毛利合计",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "\nSELECT \ndex,\nsum(a.bull-b.bull) as 卖出bull,\nsum(a.bear-b.bear) as 卖出bear,\nsum(b.usdt-a.usdt) as 赚取usdt,\nsum(b.usdt-a.usdt)-sum(a.bull-b.bull)*$3BBULL-sum(a.bear-b.bear)*$3BBEAR as \"利润\"\nfrom assets  as b\nleft join address as a\non a.account_id=b.id\n\ngroup by dex"
    }
   ]
  },
  {
   "title": "牛熊挂单",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsum(bullblock) as bulls,\nsum(bearblock) as bears \nfrom assets "
    }
   ]
  },
  {
   "title": "净值变化",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select symbol 币种,\nlastworth 前一净值,\ncurrworth 当前净值,\nlastprice 前一价格,\ncurrprice 当前价格 from worth\n"
    }
   ]
  },
  {
   "title": "头寸",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select \nexchange 交易所,\namount 数量,\npriceavg 开仓价,\nprofitreal 未实现盈亏,\nleverrate 倍数, \nforceliquprice 强平价\n\nfrom contract\n"
    }
   ]
  },
  {
   "title": "合约资",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT exchange, keep 保证金,\nprofitunreal 未实现盈亏,\naccountrights 钱包余额   from exchange"
    }
   ]
  },
  {
   "title": "毛利",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \na.alias \"使用者\",\n \nb.bull Bull现存数量 ,\na.bull-b.bull as Bull卖出数量, \nb.bear Bear现存数量,\na.bear-b.bear as Bear卖出数量, \nb.usdt Usdt现存数量,  \nb.usdt-a.usdt as Usdt赚取数量\n \nfrom assets  as b\nleft join address as a\non a.account_id=b.id"
    }
   ]
  },
  {
   "title": "地址列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "select alias, bull,bear, usdt,CONCAT('eth:',address) as 地址,create_at from address"
    }
   ]
  }
 ]
}