{
 "title": "Bee Network  ETF Balance Watch",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "牛熊差额",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsum(bear)  -sum(bull) \n \nfrom assets  \n"
    }
   ]
  },
  {
   "title": "地址资产数量",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsum(bull) as bulls,\nsum(bear) as bears,\nsum(usdt) as usdts,\nsum(eth) as eths\n\nfrom assets group by accountid\n"
    }
   ]
  },
  {
   "title": "牛熊挂单",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nsum(bullblock) as bulls,\nsum(bearblock) as bears \nfrom assets group by accountid"
    }
   ]
  },
  {
   "title": "各地址资产情况",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "rawSql": "SELECT * from assets" }
   ]
  },
  {
   "title": "地址列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "rawSql": "select * from address" }
   ]
  }
 ]
}